baseurl = "/"
languageCode = "en-us"
title = "Congressional Public Opinion Index"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "public-opinion-index"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "The Index"
    url = "/theindex/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/aaronedwardolson/congressional-public-opinion-index"

    
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "capitol.ico"

    [params.logo]
    url = "capitol.png"
    width = 50
    height = 50
    alt = "Logo"

